baseURL = "/alto/"
languageCode = "en-us"
title = "Alto"


# High level items

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Docs"
  weight = 5
  identifier = "docs"
  url = "/components/button/"

[[menu.main]]
  name = "Releases"
  weight = 10
  identifier = "releases"
  url = "/releases/"

[[menu.main]]
  name = "Storybook"
  weight = 20
  identifier = "storybook"
  url = "/storybook/"


[[menu.docs]]
  name = "Components"
  weight = 30
  identifier = "components"
  url = "/components/"

[[menu.docs]]
  name = "Patterns"
  weight = 20
  identifier = "patterns"
  url = "/patterns/"
