baseURL = "/alto/"
languageCode = "en-us"
title = "Alto"


# High level items

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Docs"
  weight = 5
  identifier = "docs"
  url = "/components/button/"

[[menu.main]]
  name = "Releases"
  weight = 10
  identifier = "releases"
  url = "/releases/"


[[menu.docs]]
  name = "Components"
  weight = 10
  identifier = "components"
  url = "/components/"

[[menu.docs]]
  name = "Utilities"
  weight = 20
  identifier = "utilities"
  url = "/utilities/"
